### ISSUE TITLE
Grpc client ?

### ISSUE THREAD

**Issue by gedw99** [pthethanh/micro#3]
Pretty clean setup

The generator looks pretty cool 

It would I think be useful to have a go based client using grpc, in order to be able to validate the working system.

I really like the way you model events using CUD pattern in the proto.

Also a 2nd thing;

I am using grpc with genji badger dB and would be able to PR it. It has subscriptions which removes the need for NATS.
It is a sql and kv dB in golang. 
It’s also possible to scale genji out with RAFT automatically.

**Comment by pthethanh** [comment]
Thank you very much for your feedback @gedw99. It's nice having someone review the code :)

For the gRPC client, the reason I don't want to include the client code in the project template is because people can easily find it from grpc-go project documentation. And I also added a simple example here: https://github.com/pthethanh/micro/tree/master/examples/helloworld/client

With regard to genji DB, could you please explain more detail what would you want to PR? I don't really know genji and RAFT hence not sure how you are using them right now. About NATS module in the micro project, it's just a implementation of the broker interface which is a message broker for communication between multiple services in a distributed system, I would be appreciate if you can contribute more implementation to the current library.

**Comment by pthethanh** [comment]
Finally, I added the client for easier to use without checking the grpc client code.

**Comment by gedw99** [comment]
> Thank you very much for your feedback @gedw99. It's nice having someone review the code :)
> 
> For the gRPC client, the reason I don't want to include the client code in the project template is because people can easily find it from grpc-go project documentation. And I also added a simple example here: https://github.com/pthethanh/micro/tree/master/examples/helloworld/client
> 
> With regard to genji DB, could you please explain more detail what would you want to PR? I don't really know genji and RAFT hence not sure how you are using them right now. About NATS module in the micro project, it's just a implementation of the broker interface which is a message broker for communication between multiple services in a distributed system, I would be appreciate if you can contribute more implementation to the current library.

sure.

Client that want to mutate the data, submit an event with payload to "Micro".
The event is stored in NATS .
Genji ( a golang in prcoess DB ) subscribes to the event, and that updates the DB based on the event payload, etc
- Because NATS groups and NATS itself is backed by RAFT you have now essentially made the DB Highly available, because you can have a 1,000 masters of the DB. Also NATS is naturally able to be clustered too using Raft, so a NATS server going down does nothing..

CLients that want to do a select can just ask for it from the Genji DB.

BTW NATS Clients automatically do load balancing and know when a nats server is removed , adding in real time.

Hope this helps.

Links

https://docs.nats.io/jetstream/clustering

https://gcoolinfo.medium.com/comparing-nats-nats-streaming-and-nats-jetstream-ec2d9f426dc8

https://github.com/genjidb/genji
